[package]
name = "calc"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"
description = "Featureful CLI calculator app"

[dependencies]
anyhow = { version = "1.0.38", optional = true }
lalrpop-util = "0.19.4"
lazy_static = "1.4.0"
regex = "1.4.3"
rustyline = { version = "7.1.0", optional = true }
structopt = { version = "0.3.21", optional = true }
thiserror = "1.0.23"

[build-dependencies]
lalrpop = "0.19.4"

[features]
default = ["cli"]
cli = [
    "anyhow",
    "rustyline",
    "structopt",
]
