[package]
name = "calc"
version = "0.4.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2021"
description = "CLI calculator app"
license = "GPL-3.0-only"
repository = "https://github.com/coriolinus/calc"
categories = [
    "command-line-interface",
    "command-line-utilities",
    "mathematics",
]
keywords = ["calculator", "cli"]

[dependencies]
anyhow = { version = "1.0.65", optional = true }
clap = { version = "4.0.14", features = ["derive"] }
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
lazy_static = "1.4.0"
num-runtime-fmt = "0.1.2"
regex = "1.6.0"
rustyline = { version = "10.0.0", optional = true }
thiserror = "1.0.37"

[build-dependencies]
lalrpop = "0.19.8"

[features]
default = ["cli"]
cli = [
    "anyhow",
    "rustyline",
]

[[bin]]
name = "calc"
required-features = ["cli"]
