on:
  release:
    types: [created]

name: Release

defaults:
  run:
    shell: bash

jobs:
  build-release-binaries:
    name: Build Release Binaries

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: RUSTFLAGS='-C link-arg=-s' cargo build --release
      - name: identify the artifact and name it per the os
        run: |
          set -e -x
          artifact="$(cut -d: -f1 < target/release/calc.d)"
          new_name="$(printf '%s-%s' "$(basename "$artifact")" "$(uname | tr '[:upper:]' '[:lower:]')")"
          mv "$artifact" "$new_name"
          echo "artifact=$new_name" >> "$GITHUB_ENV"
      - run: ls -lh "${{ env.artifact }}"
      - name: Upload the artifact
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "${{ env.artifact }}"
