on:
  release:
    types: [created]

name: Release

defaults:
  run:
    shell: bash

jobs:
  build-release-binaries:
    name: Build binaries for release
    continue-on-error: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: build
        run: RUSTFLAGS='-C link-arg=-s' cargo build --release
      - name: identify the artifact and name it per the os
        run: |
          set -e -x
          artifact="$(cut -d: -f1 < target/release/calc.d)"
          new_name="$(printf '%s-%s' "$(basename "$artifact")" "$(uname | tr '[:upper:]' '[:lower:]')")"
          mv "$artifact" "$new_name"
          echo "artifact=$new_name" >> "$GITHUB_ENV"
      - run: ls -lh "${{ env.artifact }}"
      - uses: actions/upload-artifact@v2
        with:
          name: "${{ env.artifact }}"
          path: "${{ env.artifact }}"

  upload-release-binaries:
    name: Add binaries to release
    if: always()
    needs: build-release-binaries
    continue-on-error: true

    strategy:
      matrix:
        artifact: [calc-linux, calc-darwin, calc-windows]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: "${{ matrix.artifact }}"
      - name: Add to release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "${{ matrix.artifact }}"
